# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
  repositories:
  - repository: templates
    type: git
    name: pipeline-templates
    ref: refs/tags/fixbranchname

#- repo: self
    

variables:

  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '0a93cb11-af29-4754-86aa-3374ecc129d8'
  imageRepository: 'soccerjoshjpipelinesjavascriptdocker'
  containerRegistry: 'javascriptpipelineacr.azurecr.io'
  dockerfilePath: '**/Dockerfile'
  tag: '$(Build.BuildId)'
  imagePullSecret: 'javascriptpipelineacr9566-auth'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'
  
  # Name of the new namespace being created to deploy the PR changes.
  k8sNamespaceForPR: '$(system.pullRequest.sourceBranch)'

stages:
- stage: Build
  displayName: Build stage
  jobs:  
  - template: k8s/k8s-build.yml@templates
    parameters:
      dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
      imageRepository: $(imageRepository)
      containerRegistry: $(containerRegistry)
      dockerfilePath: $(dockerfilePath)
      tag: $(tag)
      pool:
        vmImage: $(vmImageName)

- stage: Deploy
  displayName: Deploy stage
  dependsOn: Build

  jobs:
  - template: k8s/k8s-deploy.yml@templates
    parameters:
      dockerRegistryServiceConnection: $(dockerRegistryServiceConnection)
      imageRepository: $(imageRepository)
      containerRegistry: $(containerRegistry)
      tag: $(tag)
      imagePullSecret: $(imagePullSecret)
      k8sNamespaceForPR: $(k8sNamespaceForPR)
      pool:
        vmImage: $(vmImageName)